### ISSUE TITLE
Installing repository via pip

### ISSUE THREAD

**Issue by veera-puthiran-14082** [lcn-kul/xls-r-analysis-sqa#1]
I appreciate your great contribution. I was attempting to analyze the model and used the below command to install the repository via pip as a first step.

```bash
pip install git+https://github.com/lcn-kul/xls-r-analysis-sqa.git
```

Installing the repository as a package was the expected behavior. Instead I got the output.

```bash
  Collecting git+https://github.com/lcn-kul/xls-r-analysis-sqa.git
  Cloning https://github.com/lcn-kul/xls-r-analysis-sqa.git to /tmp/pip-req-build-dm4w_912
  Running command git clone --filter=blob:none --quiet https://github.com/lcn-kul/xls-r-analysis-sqa.git /tmp/pip-req-build-dm4w_912
  Resolved https://github.com/lcn-kul/xls-r-analysis-sqa.git to commit bd002b01f87e1d847942260d4113fe7c60201bda
  Preparing metadata (setup.py) ... done

```

```bash
Python 3.9.18 (main, Sep 11 2023, 13:41:44) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xls_r_sqa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'xls_r_sqa'
```

In the setup.py, directories were not included. Hopefully, resolving that will fix the problem.

after including directories

```bash
from setuptools import find_packages, setup

setup(
    name="xls_r_sqa",
    packages=find_packages(),
    version="0.1.0",
    description="Models for the paper 'Analysis of XLS-R for Speech Quality Assessment'.",
    author="Bastiaan Tamm",
    license="MIT",
    include_dirs=["xls_r_sqa"],
)

```

**Comment by btamm12** [comment]
Thanks for opening this. I added "include_dirs" to setup.py in commit a27e864

I also added version-2 of the models, should be much better than version-1. Thanks for working with the models!

**Comment by veera-puthiran-14082** [comment]
I appreciate your quick reply. I'm afraid I missed out another thing. Under the module `xls_r_sqa, `__init__.py is missing.

Also an another suggestion, can we have models under the module `xls_r_sqa` ?
